# Generated by Django 5.0.7 on 2024-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_snippet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='status',
            field=models.BooleanField(choices=[(0, 'Приватный'), (1, 'Публичный')], default=False),
        ),
    ]
