# Generated by Django 5.0.7 on 2024-07-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
